name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the deployment workflow
      run: |
        for i in {1..3}; do
          if ! $(nc -z ${{ secrets.IP }} ${{ secrets.PORT }}); then
            echo Unable to deploy
            echo IP: $(curl -s -4 icanhazip.com)  
          else
            eval "$(ssh-agent -s)"
            ssh-add - <<< "${{ secrets.KEY }}"
            echo Starting the deployment
            ssh -o StrictHostKeychecking=no \
              -o UserKnownHostsFile=/dev/null \
              -p ${{ secrets.PORT }} \
              ${{ secrets.USERNAME }}@${{ secrets.IP }} \
              touch testfile.txt
            break
          fi
          sleep 60
        done
