name: Deployment

on: [push]

#on:
#  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        echo IP: $(curl -4 icanhazip.com)
    - name: Run the deployment script
      run: |
        eval "$(ssh-agent -s)" 
        ssh-add - <<< "${{ secrets.KEY }}"
        echo deployment goes under this line
        ssh -o StrictHostKeychecking=no \
        -o UserKnownHostsFile=/dev/null \
        -p ${{ secrets.PORT }} \
        ${{ secrets.USERNAME }}@${{ secrets.IP }} \
        touch testfile.txt
