name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check the connection
      run: |
        if ! $(nc -z ${{ secrets.IP }} ${{ secrets.PORT }}); then
          echo Unable to connect
          echo IP: $(curl -s -4 icanhazip.com)
        else
          echo Connection successful
        fi
    - name: Run the deployment workflow
      run: |
        for i in {1..5}; do
          if ! $(nc -z ${{ secrets.IP }} ${{ secrets.PORT }}); then
            echo Unable to deploy, attempt ${i}/5
            sleep 30
          else
            eval "$(ssh-agent -s)"
            ssh-add - <<< "${{ secrets.KEY }}"
            echo Starting the deployment
            ssh -o StrictHostKeychecking=no \
              -o UserKnownHostsFile=/dev/null \
              -p ${{ secrets.PORT }} \
              ${{ secrets.USERNAME }}@${{ secrets.IP }} \
              touch testfile.txt
            break
          fi
        done
