name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the deployment workflow
      run: |
        if $(nc -z ${{ secrets.IP }} ${{ secrets.PORT }}); then
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${{ secrets.KEY }}"
          echo Starting the deployment
          ssh -o StrictHostKeychecking=no \
            -o UserKnownHostsFile=/dev/null \
            -p ${{ secrets.PORT }} \
            ${{ secrets.USERNAME }}@${{ secrets.IP }} \
            touch testfile.txt
        else
          echo Unable to deploy
          echo IP: $(curl -s -4 icanhazip.com)
        fi
